### ISSUE TITLE
jobPoll() doesn't handle error status

### ISSUE THREAD

**Issue by dschnare** [routific/routific-node-client#23]
When polling a job using `Routific#jobPoll`, it will poll infinitely if the job completes with a status of `error`.

https://github.com/routific/routific-node-client/blob/master/lib/client.js#L136

If the job failed then `reject` should be called like `reject(Object.assign(new Error(job.output), { job }))`.

**Comment by sjustason** [comment]
Changes to remediate this gap were merged and deployed.
